### ISSUE TITLE
Add support for Picasso data files

### ISSUE THREAD

**Issue by ZPYin** [ZPYin/polly_2_earlinet_convertor#1]
Enable to convert the netCDF files from **Picasso**

**Comment by HolgerPollyNet** [comment]
what support do you need? shall I try to code  little? So far I get this error messae:
Labview info file does not exist.
data\2020_04_12_Sun_TROPOS_00_00_01_0100_0159_profile-info.txt

when using picasso output ;-)

**Comment by ZPYin** [comment]
The conversion from Picasso to EARLINET profile is totally blank in the code base. It's sad, but it's the truth.
I leave this issue here, because I think it could be needed in the future... 

So forget about the output from the program. It's not telling you, "hey, there is bug with the conversion". It means "it's not developed at all".

You can start working on this issue if you want this funtionality now ... Or we can do it together after May 1st. 
As far as I see, we would need to adjust Picasso output to be compatible with the conversion, since there are some parameters required in EARLINET data format but missing in the nc file from Picasso. That's the most time-consuming thing.

**Comment by ZPYin** [comment]
Implemented in the master branch
